# Site Settings
title: "Silopelet"
description: "A simple Jekyll site using the Minimal Mistakes theme"
url: ""
baseurl: ""
locale: en-US

# Theme Settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "sunrise"

# Author
author:
  name: ""
  avatar: "/assets/images/silopelet-picture.png"

# Build Settings
markdown: kramdown
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Pagination
paginate: 5
paginate_path: /page:num/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
